### ISSUE TITLE
Forget password feature not working

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Felicia-Store-design---6-June-2022#18]
Bug - On entering valid email then still submit button showing disabled. 
Exp - Submit button should get enable when enter valid email.
Ref Link - https://drive.google.com/file/d/1PqkiNiEG-bp4ycdj7ZGIhDfx5-u2E-LK/view

**Comment by devSuneel** [comment]
resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
