### ISSUE TITLE
Rating star color UI isuse

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Felicia-Store-design---6-June-2022#20]
Bug - Star rating color not match with store primary color.
Exp - Star rating color should match with store primary color or make or yellow color.
Ref link - https://drive.google.com/file/d/1t5eCPT7Le9nOT68AxSQop2WgLQrfPzeZ/view

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - rating star color not mathcing with store primary color.
https://drive.google.com/file/d/1YdPpoj_sOUPz4mjuYTojqghyZIA05GCI/view

**Comment by ui-monikasingh** [comment]
Its not compulsory to use store primary color for stars

**Comment by ankitcedcoss** [comment]
Closing on Not Required !
