### ISSUE TITLE
spacing issue on footer navigation options responsive - Mobile and Tab

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Felicia-Store-design---6-June-2022#7]
Bug - Spacing issue on navigation options on footer.
Exp - Need to decrease spacing in tab and increase in mobile UI.
Ref Link - https://nimb.ws/tB7cOl
- https://nimb.ws/QeabTX

**Comment by ui-monikasingh** [comment]
@ankitcedcoss  tabs  space have been decreased , mobile spacing is fine, no need to increase the space.

**Comment by ankitcedcoss** [comment]
Bug Fixed
